version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: datadb
#      what do you mean datadb? dataDATAbase?
    ports:
      - "15433:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

